### PR TITLE
Added settings to not escape mailto links in markdown from chunks

### LINKED ISSUE #1855: Mailto links don't work in articles and chunks
## What kind of an issue is this?

- [x] Bug report
- [ ] Feature request

## What is the expected behaviour?
Mailto links should work

## What is the current behaviour?
Mailto links link to /# instead of opening email

## How do you reproduce this problem? 

Just look at any of the mailto links in the chucks, or in an article

### PR DESCRIPTION
**Pull request by oleast**
## What kind of a pull request is this?

- QA / Code Review

## Code Checklist

- [x] The code follows dotkom code style 
- [x] The code passes the defined tests
- [ ] I have added tests for the code I added
- [ ] I have provided documentation for the code I added
- [x] The code is ready to be merged

## Description of changes

Fixes #1855 

[default settings](https://github.com/trentm/django-markdown-deux/blob/master/lib/markdown_deux/conf/settings.py) for `django-markdown-deux` is to escape mailto links.

This change lets markdown render `unsafe` elements.

### CODE REVIEW

**Comment by sklirg** [comment]
Is there a way to whitelist elements rather than turning off safe mode globally for all markdown? I'm not that familiar with what you technically can achieve with markdown in terms of XSS etc., so if this is the only possible solution we should be aware of the risks.

**Comment by oleast** [comment]
It may or may not be possible to do with a [link pattern](https://github.com/trentm/python-markdown2/wiki/link-patterns)
Not sure if i understand correctly about the [default behavior](https://github.com/trentm/python-markdown2/wiki/link-patterns#default-link-behaviour), if only `http(s)` and `ftp` link are supported, or that you could write a link pattern which makes it possible.

**Comment by sklirg** [comment]
Looks like there's an open issue regarding this: https://github.com/trentm/python-markdown2/issues/257

So yeah, extending the link pattern to include mailto links sounds like the best choice in my opinion.

**Comment by sardred** [comment]
ahahahh yeah man me too i love link patterns

@oleast, do we "extend the link pattern to include mailto links", accept the potential risks of merging this, or close it?

**Comment by sardred** [comment]
Better safe than sorry! Closing and deleting branch.

**Pull request closed without merging**
