### PR TITLE
Update mark duration from 30 to 20 days

### PR DESCRIPTION
**Pull request by Thomhas**
## Description of changes

Online wishes to change the duration of a mark from 30 days to 20 days. 
## Code Checklist

- [ ] I have added tests
- [ ] I have provided documentation

## Visual changes

<details>
<summary>Before</summary>

</details>

<details>
<summary>After</summary>

</details>

### CODE REVIEW

**Comment by henrikhorluck** [comment]
It might be preferable to make the duration configurable instead, and make a db-migration so that it defaults to 30 for existing marks, so that this does not have a retroactive side-effect

**Comment by Thomhas** [comment]
The change on the mark duration should affect all marks(not only the new ones). With that in mind is it still preferable to attach the duration to the MarkRuleSet?

**Comment by anderssonw** [comment]
status? @Thomhas 😳😳😳😳😳

**Comment by Thomhas** [comment]
> status? @Thomhas 😳😳😳😳😳

Soon!

**Review by kharann — APPROVED** [review]
hacky but good as we change mark rules once every 5 years

**Pull request merged**
