### PR TITLE
Fixes provisioning bugs

### PR DESCRIPTION
**Pull request by tmn**
This PR bumps nodejs to 4.x LTS version, and installs libffi-dev

In current state the system won't provision correctly. Too old node version causes errors like (see [gist](https://gist.github.com/tmn/f5529f727a723a90f004)): 

```
cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
```

And missing **libffi-dev** causes errors on `cryptography` when `Running setup.py install for cryptography` (see [gist](https://gist.github.com/tmn/0c347d7cc36d1ed165e8)).

### CODE REVIEW

**Comment by sklirg** [comment]
For the record, libffi-dev is probably not required in provisioning after
#1260 is merged.

**Comment by tmn** [comment]
Probably?

**Comment by sklirg** [comment]
Depending on if requests[security] is required in the project. Something it has not been until now, but afaik it's a new package and might be required some time? The requirement was introduced in https://github.com/dotKom/onlineweb4/pull/1341 which were dependencies for frigg. If it's only needed for frigg, we won't include it in the required requirements.txt, but rather requirements-frigg.txt

**Comment by tmn** [comment]
Want me to create a separate PR for nodejs only? :)

**Comment by sklirg** [comment]
Nah, we'll be fine.

**Comment by sklirg** [comment]
Looks good to me, tested and it works.

**Comment by hernil** [comment]
Works indeed!

**Pull request merged**
