### PR TITLE
Make links in the about section work with anchor and on reload

### LINKED ISSUE #1706: Unable to link directly to a page in the about section on front page
Steps to reproduce:
1. Goto https://online.ntnu.no/#interessegrupper
2. Page loads as if https://online.ntnu.no was the url

### PR DESCRIPTION
**Pull request by OptimusCrime**
Fixes #1706.

Most likely a short lived fix, but the redux version could potentially reuse some of this functionality.

### CODE REVIEW

**Comment by OptimusCrime** [comment]
Also: Windows line endings :D :D :D

**Comment by sklirg** [comment]
Could you do this fix without converting the line endings at the same time? It's impossible to diff this.

If you insist on fixing EOL chars, do it in a separate commit :)

**Comment by OptimusCrime** [comment]
@sklirg I sort of fixed it now. You can see the actual diff now. However, there is one commit converting the endings to EOL, and one converting it back, so it's sort of ugly. I am not sure how to fix that git wise (rebase branch on itself?). Is that ok? I am guessing these files will vanish soon enough anyways.

**Comment by sklirg** [comment]
`git rebase -i HEAD~2`
fixup (squash with same commit message) the second commit into the first one. That will merge the changes into one commit.

This rewrites history and will therefore require a force push to this branch.

**Comment by OptimusCrime** [comment]
Did not do it for some reason. However a quick goooogle search gave me
```git reset --soft "HEAD^"
git commit --amend```

Which did the trick. All good @duvholt

**Pull request merged**
