### PR TITLE
Remove broken link in adminpanel title

### PR DESCRIPTION
**Pull request by nixolas1**
Yes.

### CODE REVIEW

**Comment by cXhristian** [comment]
Would it be possible to still have a link back to /?

**Comment by hernil** [comment]
Isn't this fixed as of now? https://online.ntnu.no/admin/

**Comment by cXhristian** [comment]
It's broken on dev.

**Comment by sklirg** [comment]
Grappelli probably decided it was smart to strip HTML tags. Which is smart.
So the link-hack doesn't work. However, there's a link that's called "View
webpage", which does the same thing.

**Comment by cXhristian** [comment]
Oh, yeah. That's true. Merging this then.

**Pull request merged**
