### PR TITLE
Issue #1346 Adding seniorkom to "Legg til Verv"+ Show year of study in dashboard

### PR DESCRIPTION
**Pull request by kharann**
## What kind of a pull request is this?
Adding Seniorkom to list of comittees in "Legg til Verv"
Adding year of study to dashboard too i guess
- QA / Code Review

## Code Checklist

- [x] The code follows dotkom code style 
- [x] The code passes the defined tests
- [x] I have added tests for the code I added
- [ ] I have provided documentation for the code I added
- [x] The code is ready to be merged

## (Possible) Breaking Changes

- [x] The changes are backwards compatible

- [ ] I have updated the build configuration
- [ ] These changes requires changes to configuration in production 
    - [ ] I have applied the required changes in production
    - [ ] I cannot apply the required changes in production before this is deployed.

## Description of changes
Just added seniorkom to that list. I checked in local adminstrator afterwards to see that the information of "seniorkom" got added to the user. I might have skipped something tho but i think it works just fine

Added year of study in dashboard for atendee list

First pull request ever, plz no bully if im bad

### CODE REVIEW

**Comment by kharann** [comment]
Heres a few screenshots too of what it changes

screenshot from 2018-09-11 01-34-48
screenshot from 2018-09-11 01-33-48
screenshot from 2018-09-11 01-33-17
screenshot from 2018-09-08 02-44-03

**Comment by torjusti** [comment]
Sorry for closing and opening your PR, I hit the button accidentally. Congratulations on your first pull request! I'll have a look at it ASAP :smile:

**Comment by oleast** [comment]
Nice to see you contributing, well done!

Since this references #1707 as well, I would just like to point to it here

**Comment by kharann** [comment]
Was thinking on referencing it, but I didn't do finish the whole request to #1707 because I haven't done the allergies part of it

**Comment by oleast** [comment]
The rest of #1707 can be accounted for in #2108.

Will just be waiting for approval from @torjusti before merging this one 😄

**Comment by kharann** [comment]
I did the commands you told me to do! Hopefully everything is in order :+1:

**Comment by torjusti** [comment]
Thanks a lot and congratulations on your first contribution! Will be in production soon.

**Comment by kharann** [comment]
Thank you! It means a lot ♥️

**Pull request merged**
