### PR TITLE
Add image field to Hobby and Resource API endpoints

### PR DESCRIPTION
**Pull request by oleast**
## What kind of a pull request is this?

- QA / Code Review

## Code Checklist

- [x] The code follows dotkom code style 
- [x] The code passes the defined tests
- [x] The code is ready to be merged

## (Possible) Breaking Changes

- [x] The changes are backwards compatible

## Description of changes

This pull request adds the image field to the `resourcecenter` and `hobbygroups` API endpoint.
This is done to make the API compatible with 'Onlineweb Frontend'.

Also added a newline to appease stylelint.

## Update:

Changed image field on resource and hobbys to use `ResponsiveImage`.
Added an image type to use for resources and hobbys.

### CODE REVIEW

**Comment by oleast** [comment]
From what I can see, that would require the models to be updated to have the foreign key of a 'ResponsiveImage', rather than the 'ImageField' they use now.

It can be done, but will require some changes in prod.

**Comment by sklirg** [comment]
Interesting. I'd vouch for that being done, so all images are handled the
same.

**Comment by MrHanSan** [comment]
@oleast could you do a rebase, or merge inn develop? Will have another look.

**Comment by oleast** [comment]
It has been rebased now, but I am a bit unsure of how we will have to do this in production?
Will we have to add a manual migration for setting a default ResponseiveImage or something like that?

**Comment by sklirg** [comment]
Correct. Everything will start with no image, so you'll have to upload a new image to each object.

**Pull request merged**
