### PR TITLE
Careeropportunity refactor rebase

### PR DESCRIPTION
**Pull request by Westermoen**
## What kind of a pull request is this?

- [x] QA / Code Review

## Code Checklist

- [x] The code follows dotkom code style 
- [x] The code passes the defined tests
- [x] The code is ready to be merged

## (Possible) Breaking Changes

- [x] The changes are backwards compatible

## Description of changes

refactored careeropportunities in react

### CODE REVIEW

**Comment by OptimusCrime** [comment]
Did you merge instead of rebase?

**Comment by sklirg** [comment]
Yes, intentionally. Rebasing a lot of commits that were done over half a year ago is very much work. Can squash merge it instead.

**Comment by sklirg** [comment]
> /drone/src/github.com/*****/onlineweb4/assets/careeropportunity/components/Tag.js
>  5:3  error  Visible, non-interactive elements should not have mouse or keyboard event listeners  jsx-a11y/no-static-element-interactions

Needs fix:)

**Comment by sklirg** [comment]
Closing in favor of #1833.

**Pull request closed without merging**
