### PR TITLE
Add Frigg CI

### PR DESCRIPTION
**Pull request by frecar**
This PR adds a .frigg.yml config file to run onlineweb4 tests.

The current build is failing, becuase the project contains pep8 and isort issues. 

All you need to do to integrate with Frigg is to do the following: 

- Add Github Webhook
    - Go to your project repository on Github
    - Click Settings
    - Click Webhooks & Services
    - Click Add Webhook

- Add http://ci.frigg.io/webhooks/github/ as the Payload URL
    - Set Content Type to application/json
    - Click on Send me everything
    - Click Update webhook

Then you can visit https://ci.frigg.io to see build status, Frigg will also report on all PRs. 

@lizter

### CODE REVIEW

**Comment by frecar** [comment]
See https://frigg.io/docs/ for more docs

**Comment by frecar** [comment]
You may also take a look at: https://ci.frigg.io/frecar/onlineweb4/34/ to see how this will work.

**Comment by myth** [comment]
Looks cool! We'll take a look at it at our next meeting.

**Comment by frecar** [comment]
Sweet, and by the way; If you want more speed, you can easily set up your own dedicated workers :) Frigg aims to be a collaboration where organizations configure workers for their own and for others to use :)

**Comment by hernil** [comment]
Thanks a lot for the PR. We're looking forward to testing this more! :)

**Comment by frecar** [comment]
Cool, please let me know if you run into any problems! :)

**Pull request merged**
