### PR TITLE
[WIP] Django 1.9

### LINKED ISSUE #1376: Replace django-chunks
We should replace [django-chunks](https://github.com/clintecker/django-chunks). It's not actively maintained and it fails on Django 1.9 because it uses deprecated functions.

Our uses:
1. Frontpage, infotext regarding each committee.
2. Information texts for Offline

The functionality of 1 is scheduled to be removed in #1209 (frontpage, about all committees).
The functionality of 2 needs to be completely replaced.

As of now this module is hindering a Django version upgrade so we might want to do some temporary fix for this, and implement the change coming in #1209 at a later time. This way, we can upgrade to Django 1.9 asap.

Suggestion for temporary fixes:
- Install https://github.com/funkybob/django-flatblocks and port the data over to that module (or another similar module)
- Move current chunks into the html-templates, effectively hard-coding them into there for the time being (this removes edit-functionality from the administration panel for the time being)
- Flatpage for "about us"

### PR DESCRIPTION
**Pull request by sklirg**
Fixes #1376

f0c6dc5 Implements various models cleanup: 
Registering -> Registering of models (reversion, watson) are done in appconfig.ready(), when Django says the application is ready.
Signals -> signals.py (hooks, e.g. post_save, post-delete)
Tasks -> tasks.py (tasks which modifies a model instance)

Release notes for Django 1.9: https://docs.djangoproject.com/en/1.9/releases/1.9/

ToDo:

- [x] #1376 
- Fix deprecation warnings for Django 1.10
  - [ ] url configs

### CODE REVIEW

**Comment by myth** [comment]
Great work!

**Comment by sklirg** [comment]
The django-chunks fix requires migrations to be faked when ran.

**Comment by sklirg** [comment]
Actual tests failing this time. :+1: It has to do with templates, and as Django swapped out its own template system for a multitude of choices (including its own), that's probably the root cause. I won't have time to look at it, any takers?

**Comment by cXhristian** [comment]
Fixed original errors. Now we're getting lessc errors. 
This is likely because of the following code in base.py:

```
COMPRESS_PRECOMPILERS = (
    ('text/less', 'lessc --include-path=%s {infile} {outfile}' % DJANGO_WIKI_STATIC),
)
```

Not sure why the tests didn't fail before and I don't really know how to fix this.

**Comment by cXhristian** [comment]
:tada:

**Comment by myth** [comment]
:+1:

**Comment by cXhristian** [comment]
Django-filebrowser does not support Django 1.9 yet. I just made a pull request so let's hope it gets merged.

**Pull request closed without merging**
