### PR TITLE
Fixed space between event text and event information

### PR DESCRIPTION
**Pull request by niklasmh**
Fixed the issue for both desktop and mobile with float: right; on the event-status. Everything now looks like before just with less space as requested. (Dubplicate of [#1448](https://github.com/dotKom/onlineweb4/pull/1448))

### CODE REVIEW

**Comment by hernil** [comment]
Print screens in the PR are great for illustrating design changes like these btw. :smile:

**Comment by niklasmh** [comment]
Width more than or equal 992px:
image

Width less than 992px:
image

**Comment by niklasmh** [comment]
Also one last situation; When the event status (orange box) makes the right side taller than the event text on the left:
image

**Comment by OptimusCrime** [comment]
Hmmm, that is not good. Perhaps make the final box there float to the left for wide devices or something?

**Comment by niklasmh** [comment]
It is a really rare situation, but I agree, it should not happen.

**Comment by niklasmh** [comment]
Now it is fixed and looks like this in the same situation:
image

**Pull request merged**
