### PR TITLE
Closer eventtext

### PR DESCRIPTION
**Pull request by niklasmh**
Fixed the issue for both desktop and mobile with float: right; on the event-status. Everything now looks like before with just less space as requested.

### CODE REVIEW

**Comment by OptimusCrime** [comment]
You have included work from another branch. Also, if you fix this, do you mind supplying some images? :)

**Comment by niklasmh** [comment]
I was wondering why the commits appeared at all. They must have followed somehow when I stashed then switched branch. Is there any way of removing them from this issue?

**Comment by OptimusCrime** [comment]
My guess is that you branched out from the old branch. Because this is such a small pull, the easiest (by far) is simply to change to develop, branch out to a new branch and copy&paste the content from this fix in.

**Comment by niklasmh** [comment]
Width more than or equal 992px:
image

Width less than 992px:
image

**Comment by OptimusCrime** [comment]
Damn, that actually looks very, very nice! :clap:

**Comment by niklasmh** [comment]
Thanks! About the commits, is there any possibility to just delete this pull and create a totally new one? Or do we loose some important history by doing that?

**Comment by OptimusCrime** [comment]
Nah, just do it. Refer to this one and post the images in the new one. Should be good.

**Comment by sklirg** [comment]
"Delete" means close this PR and open a new one from the new branch you
made.

**Comment by niklasmh** [comment]
I think I understood the process now. It will be pushed in a few minutes.

**Comment by niklasmh** [comment]
Should I delete this PR? It is linked and will remain in the history books!

**Pull request closed without merging**
