### PR TITLE
Dashboard for authentication app

### PR DESCRIPTION
**Pull request by sklirg**
Initial dashboard app for `apps.authentication`.

screenshot 2015-10-18 05 50 36

ToDo:
- [x] Lists
- [x] View profile
- [x] Edit profile
- [x] Searching

### CODE REVIEW

**Comment by frecar** [comment]
Please rebase with master branch to make this work with Frigg

**Comment by sklirg** [comment]
@frecar We don't have master :trollface: 

I'll fix it.

**Comment by hernil** [comment]
"NoReverseMatch at /dashboard/auth/user/X/edit"

I get this when trying to edit a user from the dashboard.

**Comment by hernil** [comment]
Also, did you look into using watson for search?

**Comment by myth** [comment]
@frecar seems like there was a connection reset by peer during the tests. Have any input? Also, seems like the SSL package used by request is missing.

**Comment by sklirg** [comment]
Interesting, I'll have a look at it.

**Comment by frecar** [comment]
@myth: Please try to add requests[security]==2.8.0 to requirements.txt

**Comment by frecar** [comment]
You should also upgrade to latest version of django_extensions(1.5.9), to avoid the problem with south_migrations and django 1.8.6

**Comment by frecar** [comment]
Great, the only thing missing now is to fix all pep8/flake8 issues in the project :)

**Comment by sklirg** [comment]
@frecar Yes! And before we can do that, we have to merge the WIP branch #1099. So we'll have to live with some "failed" builds for now, or up the acceptable error limit so we can see the beautiful green checkmarks until that branch is merged. ;)

**Comment by frecar** [comment]
Okey, I guess you have control! ;) 

However, I would not recommend to change the limit, but fix the errors asap instead!

**Comment by cXhristian** [comment]
Yeah, let's not change the limit. That's how we ended up with this mess to begin with.

**Comment by hernil** [comment]
I agree on not raising the limit. There's also a couple of other issues regarding complexity that we should fix as well.

**Comment by sklirg** [comment]
I totally agree, however, the branch is not ready for merge yet so we cannot merge it, therefore we can't PEP8 it.

**Pull request merged**
