### PR TITLE
[DO NOT MERGE] Add initial gitattributes file to projects

### LINKED ISSUE #1741: Convert all line endings from CRLF to LF
```
 M files/static/img/online_logo.svg
 M files/static/js/OfflineWidget.js
 M files/static/js/init.js
 M files/static/js/initFrontpage.js
 M files/static/js/libs/jqplot/jqplot.barRenderer.min.js
 M files/static/js/libs/jqplot/jqplot.categoryAxisRenderer.min.js
 M files/static/js/libs/jqplot/jqplot.pieRenderer.min.js
 M files/static/js/libs/jqplot/jqplot.pointLabels.min.js
 M files/static/js/libs/jqplot/jquery.jqplot.min.js
 M files/static/js/libs/jquery-1.8.2.min.js
 M files/static/js/libs/less.js
 M files/static/js/saldo.js
 M files/static/js/splash/jquery.js
 M files/static/js/splash/main.js
 M files/static/js/splash/online-notifier.js
 M files/static/js/webshop.js
 M files/static/less/business.less
 M files/static/less/career.less
 M files/static/less/colors.less
 M files/static/less/core.less
 M files/static/less/eventwidget.less
 M files/static/less/navbar.less
 M files/static/less/offlinewidget.less
 M files/static/mimg/browserconfig.xml
 M files/static/mock/events.json
 M templates/base.html
```

consists of CRLF instead of LF.
When committing changes you might get a diff of the whole file instead of your changes, for example if your editor is set to a specific EOL.

There's no reason to have different EOL characters in our code base, so we should probably fix the ones failing.

The changes for these files are approx. 4.500 lines in total.

### PR DESCRIPTION
**Pull request by OptimusCrime**
A step along the way to fix #1741

### CODE REVIEW

**Comment by sklirg** [comment]
Won't this force all line endings to LF when it's merged, so that the next commit will contain 4500 changes which are line endings?

**Comment by OptimusCrime** [comment]
This should be merged AFTER the initial cleanup. It is meant as a tool to avoid this (mixed line endings) in the future.

**Comment by sklirg** [comment]
Aha, figures

On Thu, 20 Oct 2016, 23:42 OptimusCrime, <notifications@github.com> wrote:

This should be merged AFTER the initial cleanup. It is meant as a tool to
avoid this (mixed line endings) in the future.

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/dotKom/onlineweb4/pull/1744#issuecomment-255236595>,
or mute
the thread

**Comment by sklirg** [comment]
MERGING A DNM PR LEL

**Pull request merged**
